# -*- coding: utf-8 -*-
from __future__ import annotations

COMMON = [
    ("show version", "نسخه، uptime، image"),
    ("show running-config", "پیکربندی فعال"),
    ("show startup-config", "startup NVRAM"),
    ("show ip interface brief", "IP و وضعیت اینترفیس‌ها"),
    ("show interfaces status", "VLAN/speed/duplex/status"),
    ("show interfaces GigabitEthernet0/1", "counters، errors، drops"),
    ("show ip route", "جدول مسیر"),
    ("show ip arp", "ARP"),
    ("show mac address-table", "جدول MAC"),
    ("show logging | last 50", "۵۰ لاگ آخر"),
    ("show processes cpu sorted | exclude 0.00", "CPU"),
    ("show processes memory sorted", "RAM"),
    ("show inventory", "سخت‌افزار/SFP"),
    ("copy running-config startup-config", "ذخیره"),
    ("copy running-config tftp://10.0.0.50/backup.cfg", "بکاپ TFTP"),
    ("configure terminal", "ورود config"),
    ("end", "خروج به EXEC"),
]

BANKS = {
"vlan": [
    ("show vlan brief", "لیست VLAN و پورت‌ها"),
    ("show vlan id 10", "جزئیات VLAN 10"),
    ("show interfaces trunk", "ترانک، allowed، native"),
    ("show interfaces switchport", "access/trunk membership"),
    ("show mac address-table vlan 10", "MAC در VLAN 10"),
    ("show spanning-tree vlan 10", "STP VLAN 10"),
    ("vlan 10", "ایجاد VLAN 10"),
    ("name USERS", "نام VLAN"),
    ("vlan 20", "ایجاد VLAN 20"),
    ("name SERVERS", "نام سرورها"),
    ("vlan 99", "Native/MGMT"),
    ("name NATIVE", "نام native"),
    ("interface range GigabitEthernet0/1-24", "بازه پورت"),
    ("switchport mode access", "حالت access"),
    ("switchport access vlan 10", "عضویت VLAN 10"),
    ("spanning-tree portfast", "PortFast"),
    ("spanning-tree bpduguard enable", "BPDU Guard"),
    ("interface GigabitEthernet0/48", "پورت ترانک"),
    ("switchport mode trunk", "trunk"),
    ("switchport trunk encapsulation dot1q", "dot1q"),
    ("switchport trunk allowed vlan 10,20,30,99", "allowed list"),
    ("switchport trunk native vlan 99", "native"),
    ("switchport nonegotiate", "قطع DTP"),
    ("no shutdown", "فعال پورت"),
    ("interface Vlan10", "SVI"),
    ("ip address 10.10.10.1 255.255.255.0", "gateway VLAN"),
    ("ip helper-address 10.0.0.10", "DHCP Relay"),
    ("vtp mode transparent", "VTP transparent"),
    ("show vtp status", "وضعیت VTP"),
    ("show interfaces counters errors", "خطاهای FCS"),
    ("/interface bridge vlan print", "VLAN bridge ROS"),
    ("/interface bridge port print", "پورت bridge ROS"),
    ("/interface vlan add name=vlan10 interface=bridge1 vlan-id=10", "VLAN IF ROS"),
    ("/ip address add address=10.10.10.1/24 interface=vlan10", "IP روی VLAN ROS"),
],
"ospf": [
    ("show ip ospf", "فرآیند و RID"),
    ("show ip ospf neighbor", "همسایه‌ها"),
    ("show ip ospf neighbor detail", "timers و state"),
    ("show ip ospf interface brief", "اینترفیس‌های OSPF"),
    ("show ip ospf interface GigabitEthernet0/0", "network type، cost، DR"),
    ("show ip ospf database", "LSA DB"),
    ("show ip ospf database router", "Router LSA"),
    ("show ip ospf database network", "Network LSA"),
    ("show ip ospf database summary", "Summary LSA"),
    ("show ip ospf database external", "External LSA"),
    ("show ip route ospf", "مسیرهای OSPF"),
    ("show ip ospf border-routers", "ABR/ASBR"),
    ("router ospf 1", "فرآیند 1"),
    ("router-id 1.1.1.1", "RID ثابت"),
    ("network 10.0.0.0 0.0.0.255 area 0", "Area 0"),
    ("network 10.1.0.0 0.0.255.255 area 1", "Area 1"),
    ("area 1 stub", "Stub"),
    ("area 1 nssa", "NSSA"),
    ("area 1 range-summary", "خلاصه ABR"),
    ("passive-interface default", "passive همه"),
    ("no passive-interface GigabitEthernet0/0", "فعال adjacency"),
    ("ip ospf cost 10", "هزینه"),
    ("ip ospf network point-to-point", "P2P"),
    ("ip ospf hello-interval 5", "Hello"),
    ("ip ospf dead-interval 20", "Dead"),
    ("ip ospf authentication message-digest", "MD5 auth"),
    ("ip ospf message-digest-key 1 md5 SECRET", "کلید"),
    ("default-information originate", "default"),
    ("auto-cost reference-bandwidth 10000", "ref-bw 10G"),
    ("clear ip ospf process", "ریست فرآیند"),
    ("debug ip ospf adj", "debug Lab"),
    ("undebug all", "خاموش debug"),
    ("/routing ospf neighbor print", "Neighbor ROS"),
    ("vtysh -c 'show ip ospf neighbor'", "FRR Linux"),
],
"bgp": [
    ("show ip bgp summary", "خلاصه peer"),
    ("show ip bgp", "جدول BGP"),
    ("show ip bgp neighbors 203.0.113.2", "جزئیات peer"),
    ("show ip bgp neighbors 203.0.113.2 advertised-routes", "اعلان‌شده"),
    ("show ip bgp neighbors 203.0.113.2 received-routes", "دریافتی"),
    ("show ip route bgp", "مسیر BGP در RIB"),
    ("router bgp 65001", "AS 65001"),
    ("bgp router-id 1.1.1.1", "RID"),
    ("bgp log-neighbor-changes", "لاگ peer"),
    ("neighbor 203.0.113.2 remote-as 65002", "eBGP"),
    ("neighbor 203.0.113.2 description ISP-A", "توضیح"),
    ("neighbor 10.0.0.2 remote-as 65001", "iBGP"),
    ("neighbor 10.0.0.2 update-source Loopback0", "update-source"),
    ("neighbor 10.0.0.2 next-hop-self", "next-hop-self"),
    ("network 192.0.2.0 mask 255.255.255.0", "اعلان پیشوند"),
    ("ip prefix-list PL-OUT permit 192.0.2.0/24", "prefix-list"),
    ("route-map RM-OUT permit 10", "route-map"),
    ("match ip address prefix-list PL-OUT", "match"),
    ("set community 65001:100", "community"),
    ("neighbor 203.0.113.2 route-map RM-OUT out", "اعمال out"),
    ("clear ip bgp 203.0.113.2 soft out", "soft clear"),
    ("maximum-paths 4", "ECMP"),
    ("/routing bgp connection print", "BGP ROS"),
],
"nat": [
    ("show ip nat translations", "جدول NAT"),
    ("show ip nat translations verbose", "جزئیات"),
    ("show ip nat statistics", "آمار"),
    ("clear ip nat translation *", "پاک جدول"),
    ("ip access-list standard NAT-ACL", "ACL NAT"),
    ("permit 10.0.0.0 0.255.255.255", "شبکه داخلی"),
    ("ip nat inside source list NAT-ACL interface GigabitEthernet0/0 overload", "PAT"),
    ("ip nat inside source static 10.0.0.50 203.0.113.50", "static 1:1"),
    ("ip nat inside source static tcp 10.0.0.50 443 203.0.113.50 443 extendable", "static PAT"),
    ("interface GigabitEthernet0/1", "inside IF"),
    ("ip nat inside", "inside"),
    ("interface GigabitEthernet0/0", "outside IF"),
    ("ip nat outside", "outside"),
    ("/ip firewall nat print detail", "NAT ROS"),
    ("/ip firewall nat add chain=srcnat out-interface=ether1 action=masquerade", "masquerade"),
    ("iptables -t nat -L -n -v", "iptables NAT"),
    ("nft list table ip nat", "nft NAT"),
],
"vpn": [
    ("show crypto isakmp sa", "Phase1"),
    ("show crypto ipsec sa", "Phase2"),
    ("show crypto session detail", "جلسات"),
    ("show crypto map", "crypto map"),
    ("crypto isakmp policy 10", "IKE policy"),
    ("encryption aes 256", "AES256"),
    ("hash sha256", "SHA256"),
    ("authentication pre-share", "PSK"),
    ("group 14", "DH14"),
    ("crypto isakmp key SECRET address 203.0.113.2", "کلید peer"),
    ("crypto ipsec transform-set TS esp-aes 256 esp-sha256-hmac", "TS"),
    ("mode tunnel", "tunnel mode"),
    ("access-list 100 permit ip 10.0.0.0 0.0.0.255 10.1.0.0 0.0.0.255", "interesting traffic"),
    ("crypto map CM 10 ipsec-isakmp", "crypto map"),
    ("set peer 203.0.113.2", "peer"),
    ("set transform-set TS", "set TS"),
    ("match address 100", "match ACL"),
    ("interface GigabitEthernet0/0", "اعمال map"),
    ("crypto map CM", "روی IF"),
    ("diagnose vpn ike gateway list", "Forti IKE"),
    ("diagnose vpn tunnel list", "Forti tunnel"),
    ("get vpn ipsec tunnel summary", "خلاصه Forti IPsec"),
],
"dhcp": [
    ("show ip dhcp binding", "leaseها"),
    ("show ip dhcp pool", "pool و utilization"),
    ("show ip dhcp conflict", "conflict"),
    ("show ip dhcp server statistics", "آمار"),
    ("ip dhcp excluded-address 10.0.0.1 10.0.0.20", "excluded"),
    ("ip dhcp pool USERS", "pool"),
    ("network 10.0.0.0 255.255.255.0", "network"),
    ("default-router 10.0.0.1", "gateway"),
    ("dns-server 10.0.0.10 8.8.8.8", "DNS"),
    ("domain-name corp.local", "domain"),
    ("lease 0 8", "۸ ساعت"),
    ("option 150 ip 10.0.0.20", "option 150"),
    ("ip helper-address 10.0.0.10", "relay"),
    ("/ip dhcp-server print", "DHCP ROS"),
    ("/ip dhcp-server lease print", "lease ROS"),
    ("Get-DhcpServerv4Lease -ScopeId 10.0.0.0", "PS DHCP"),
],
"firewall": [
    ("get system status", "وضعیت Forti"),
    ("get system performance status", "CPU/RAM/Sessions"),
    ("show firewall policy", "سیاست‌ها"),
    ("show firewall policy 10", "policy 10"),
    ("diagnose sniffer packet any 'host 10.10.10.10 and port 443' 4 50 l", "sniffer ۵۰ بسته"),
    ("diagnose debug enable", "debug on"),
    ("diagnose debug flow filter addr 10.10.10.10", "filter flow"),
    ("diagnose debug flow trace start 100", "trace ۱۰۰"),
    ("diagnose debug flow trace stop", "stop trace"),
    ("diagnose debug disable", "debug off"),
    ("get router info routing-table all", "مسیر Forti"),
    ("execute ping 8.8.8.8", "ping"),
    ("execute traceroute 8.8.8.8", "trace"),
    ("iptables -L -n -v", "iptables"),
    ("nft list ruleset", "nftables"),
    ("/ip firewall filter print", "filter ROS"),
    ("/ip firewall connection print", "conntrack ROS"),
],
"stp": [
    ("show spanning-tree", "STP همه VLAN"),
    ("show spanning-tree vlan 10 root", "Root VLAN 10"),
    ("show spanning-tree vlan 10 detail", "جزئیات"),
    ("show spanning-tree inconsistentports", "inconsistent"),
    ("show spanning-tree blockedports", "blocking"),
    ("spanning-tree mode rapid-pvst", "Rapid-PVST"),
    ("spanning-tree vlan 1-4094 priority 4096", "priority Root"),
    ("spanning-tree vlan 10 root primary", "root primary"),
    ("spanning-tree portfast", "portfast"),
    ("spanning-tree bpduguard enable", "bpduguard"),
    ("spanning-tree guard root", "root guard"),
    ("spanning-tree guard loop", "loop guard"),
    ("spanning-tree vlan 10 cost 19", "cost"),
],
"linux": [
    ("ip -br a", "آدرس brief"),
    ("ip -br link", "لینک"),
    ("ip route", "مسیر"),
    ("ip route get 8.8.8.8", "مسیر به مقصد"),
    ("ss -tulpn", "listen sockets"),
    ("ss -tan state established", "established"),
    ("ping -c 4 -W 2 8.8.8.8", "ping"),
    ("traceroute -n 8.8.8.8", "traceroute"),
    ("mtr -rwzc 50 8.8.8.8", "mtr"),
    ("tcpdump -i any -nn -vv host 10.10.10.10 -c 50", "tcpdump"),
    ("tcpdump -i eth0 -nn port 53 -c 20", "DNS capture"),
    ("journalctl -xe -n 100", "journal"),
    ("journalctl -u sshd -n 50 --no-pager", "sshd log"),
    ("systemctl status sshd", "sshd status"),
    ("resolvectl status", "resolved"),
    ("nft list ruleset", "nft"),
    ("iptables-save", "iptables dump"),
    ("sysctl net.ipv4.ip_forward", "ip_forward"),
    ("ethtool eth0", "NIC"),
    ("nmcli device status", "NM devices"),
],
"windows": [
    ("ipconfig /all", "IP کامل"),
    ("ipconfig /flushdns", "flush DNS"),
    ("ipconfig /registerdns", "register DNS"),
    ("Get-NetIPAddress", "IP PS"),
    ("Get-NetRoute -AddressFamily IPv4", "route"),
    ("Test-NetConnection 8.8.8.8 -Port 443", "test 443"),
    ("Resolve-DnsName example.com -Type A", "DNS PS"),
    ("Get-NetTCPConnection -State Established", "TCP"),
    ("netstat -ano", "netstat"),
    ("gpresult /r", "GPO result"),
    ("gpresult /h C:\\Temp\\gpo.html", "GPO HTML"),
    ("gpupdate /force", "gpupdate"),
    ("nltest /dsgetdc:", "DC"),
    ("klist", "Kerberos tickets"),
    ("w32tm /query /status", "time"),
    ("w32tm /resync", "resync time"),
    ("route print", "routes"),
    ("arp -a", "ARP"),
],
"ha": [
    ("show standby brief", "HSRP brief"),
    ("show standby", "HSRP detail"),
    ("show vrrp brief", "VRRP"),
    ("standby 1 ip 10.0.0.1", "VIP"),
    ("standby 1 priority 110", "priority"),
    ("standby 1 preempt", "preempt"),
    ("standby 1 timers 1 3", "timers"),
    ("standby 1 track GigabitEthernet0/1 20", "track"),
    ("get system ha status", "Forti HA"),
    ("diagnose sys ha checksum cluster", "HA checksum"),
],
"acl": [
    ("show access-lists", "همه ACL + hit"),
    ("show ip access-lists", "IP ACL"),
    ("ip access-list extended BLOCK-RFC1918-IN", "extended ACL"),
    ("deny ip 10.0.0.0 0.255.255.255 any", "deny 10/8"),
    ("deny ip 172.16.0.0 0.15.255.255 any", "deny 172.16/12"),
    ("deny ip 192.168.0.0 0.0.255.255 any", "deny 192.168/16"),
    ("permit tcp any any eq 443", "allow HTTPS"),
    ("permit tcp any any eq 80", "allow HTTP"),
    ("deny ip any any log", "deny log"),
    ("ip access-group BLOCK-RFC1918-IN in", "apply in"),
],
"qos": [
    ("show class-map", "class-map"),
    ("show policy-map", "policy-map"),
    ("show policy-map interface", "applied + counters"),
    ("class-map match-any VOICE", "VOICE class"),
    ("match dscp ef", "EF"),
    ("policy-map QOS-OUT", "policy"),
    ("class VOICE", "class VOICE"),
    ("priority percent 15", "LLQ 15%"),
    ("bandwidth percent 30", "CBWFQ 30%"),
    ("service-policy output QOS-OUT", "apply out"),
],
"wireless": [
    ("show ap summary", "AP list"),
    ("show wlan summary", "WLAN"),
    ("show client summary", "clients"),
    ("show ap config general AP01", "AP config"),
    ("show rogue ap summary", "rogue"),
],
}

ERRORS = {
"vlan": [
    ("کلاینت IP از VLAN اشتباه", "access vlan یا native", "show vlan brief ; show interfaces switchport"),
    ("ترانک up نیست", "allowed/mode ناهماهنگ", "show interfaces trunk"),
    ("MAC نیست", "err-disabled یا VLAN غلط", "show interfaces status ; show mac address-table"),
    ("Broadcast storm", "Loop بدون STP", "show spanning-tree ; show interface counters"),
],
"ospf": [
    ("Neighbor 2-WAY", "network type/priority", "show ip ospf neighbor detail"),
    ("FULL نمی‌شود", "area/timer/MTU/auth", "show ip ospf interface"),
    ("مسیر نیست", "LSA/filter/redistribute", "show ip ospf database"),
    ("RID تکراری", "دو روتر یک RID", "show ip ospf | include ID"),
],
"bgp": [
    ("Idle/Active", "TCP179/AS/reachability", "show ip bgp summary"),
    ("اعلان نمی‌شود", "network/route-map/next-hop", "show ip bgp neighbors x advertised-routes"),
],
"nat": [
    ("بدون translation", "inside/outside/ACL", "show ip nat statistics"),
    ("یک‌طرفه", "مسیر برگشت/FW", "show ip nat translations"),
],
"vpn": [
    ("Phase1 down", "PSK/proposal/UDP500", "show crypto isakmp sa"),
    ("Phase2 down", "ACL/transform/PFS", "show crypto ipsec sa"),
],
"dhcp": [
    ("APIPA", "relay/pool/VLAN", "show ip dhcp binding"),
    ("conflict", "static+dynamic", "show ip dhcp conflict"),
],
"firewall": [
    ("hit=0", "ترتیب/آدرس/interface", "diagnose debug flow"),
    ("High CPU", "session/IPS", "get system performance status"),
],
"linux": [
    ("سرویس down", "unit/journal", "systemctl status ; journalctl -u X"),
    ("پورت بسته", "سرویس/فایروال", "ss -tulpn ; nft list ruleset"),
],
"windows": [
    ("GPO اعمال نشد", "OU/link/gpupdate", "gpresult /h report.html"),
    ("clock skew", "NTP", "w32tm /query /status"),
],
"stp": [
    ("Loop/storm", "BPDU Guard", "show spanning-tree"),
    ("Root غیرمنتظره", "priority لبه", "show spanning-tree root"),
],
}
