# -*- coding: utf-8 -*-
"""Banks of reusable lesson fragments for densify engine."""
from __future__ import annotations

# list of (command, description) — deep_fallback does COMMON[:8] and _fmt()
COMMON = [
    ("show version", "نسخه نرم‌افزار و uptime"),
    ("show ip interface brief", "وضعیت رابط‌ها و IP"),
    ("show running-config | include hostname", "نام دستگاه"),
    ("show logging | last 50", "آخرین رخدادها"),
    ("ping 8.8.8.8", "تست دسترس‌پذیری پایه"),
    ("traceroute 8.8.8.8", "مسیر لایه ۳"),
    ("show ip route", "جدول مسیریابی"),
    ("show arp", "نگاشت IP به MAC"),
    ("show cdp neighbors", "همسایه‌های کشف‌شده"),
    ("show interfaces status", "وضعیت لینک و VLAN"),
]

BANKS = {
    "vlan": {"summary": "جداسازی منطقی لایه ۲.", "lab": "ساخت VLAN و assign پورت.", "cmds": [("show vlan brief", "فهرست VLAN"), ("show interfaces trunk", "وضعیت trunk")]},
    "ospf": {"summary": "مسیریابی لینک‌استیت.", "lab": "دو روتر OSPF area 0.", "cmds": [("show ip ospf neighbor", "همسایه‌ها"), ("show ip route ospf", "مسیرهای OSPF")]},
    "bgp": {"summary": "مسیریابی بین‌دامنه‌ای.", "lab": "eBGP peer در Lab.", "cmds": [("show ip bgp summary", "وضعیت peer"), ("show ip bgp", "جدول BGP")]},
    "nat": {"summary": "ترجمه آدرس.", "lab": "PAT روی لبه.", "cmds": [("show ip nat translations", "ترجمه‌ها"), ("show ip nat statistics", "آمار NAT")]},
    "vpn": {"summary": "تونل امن.", "lab": "IPsec آزمایشی.", "cmds": [("show crypto session", "نشست VPN"), ("show crypto isakmp sa", "Phase1")]},
    "dhcp": {"summary": "تخصیص خودکار IP.", "lab": "pool و binding.", "cmds": [("show ip dhcp binding", "اجاره‌ها"), ("show ip dhcp pool", "استخر")]},
    "firewall": {"summary": "فیلتر ترافیک.", "lab": "قانون allow/deny.", "cmds": [("show access-lists", "ACLها"), ("show logging | include %SEC", "لاگ امنیت")]},
    "stp": {"summary": "جلوگیری از حلقه لایه ۲.", "lab": "بررسی root.", "cmds": [("show spanning-tree", "وضعیت STP"), ("show spanning-tree root", "Root bridge")]},
    "dns": {"summary": "نام به آدرس.", "lab": "query A/AAAA.", "cmds": [("nslookup example.com", "resolve نام"), ("dig +short example.com", "پاسخ کوتاه")]},
    "wireless": {"summary": "WLAN و امنیت Wi-Fi.", "lab": "مشاهده interface.", "cmds": [("netsh wlan show interfaces", "وضعیت وای‌فای"), ("iw dev", "رابط‌های بی‌سیم")]},
    "python": {"summary": "اتوماسیون شبکه.", "lab": "اتصال read-only.", "cmds": [("python -c \"print('ok')\"", "تست پایتون")]},
    "ansible": {"summary": "پیکربندی اعلانی.", "lab": "ansible ping.", "cmds": [("ansible all -m ping", "تست inventory")]},
    "general": {"summary": "موضوع عمومی شبکه/IT.", "lab": "مشاهده و ثبت شواهد.", "cmds": COMMON[:4]},
    "linux": {"summary": "سیستم‌عامل لینوکس.", "lab": "journalctl و ss.", "cmds": [("ip a", "آدرس‌ها"), ("ss -tulpn", "سوکت‌ها"), ("journalctl -xe", "لاگ")]},
    "windows": {"summary": "ویندوز سرور/کلاینت.", "lab": "ipconfig و eventlog.", "cmds": [("ipconfig /all", "پیکربندی IP"), ("Get-EventLog -LogName System -Newest 20", "رویدادها")]},
    "ha": {"summary": "دسترس‌پذیری بالا.", "lab": "HSRP/VRRP آزمایشی.", "cmds": [("show standby", "وضعیت HSRP")]},
    "security": {"summary": "کنترل دسترسی و AAA.", "lab": "بررسی 802.1X/RADIUS.", "cmds": [("show aaa servers", "سرورهای AAA")]},
    "tcpip": {"summary": "TCP/IP پایه.", "lab": "ping و traceroute.", "cmds": [("ping 8.8.8.8", "ICMP"), ("traceroute 8.8.8.8", "مسیر")]},
    "storage": {"summary": "ذخیره‌سازی.", "lab": "latency و path.", "cmds": [("# check disk latency", "مانیتورینگ دیسک")]},
    "virtualization": {"summary": "مجازی‌سازی.", "lab": "وضعیت VM/vSwitch.", "cmds": [("# esxcli network", "شبکه ESXi")]},
    "mikrotik": {"summary": "RouterOS.", "lab": "/ip address print.", "cmds": [("/ip address print", "آدرس‌ها"), ("/interface print", "رابط‌ها")]},
    "fortigate": {"summary": "FortiGate.", "lab": "policy و session.", "cmds": [("get system status", "وضعیت"), ("diagnose firewall", "فایروال")]},
    "ad": {"summary": "Active Directory.", "lab": "replication و DNS.", "cmds": [("repadmin /showrepl", "replication")]},
    "python": {"summary": "اتوماسیون پایتون.", "lab": "اسکریپت read-only.", "cmds": [("python -c \"print(1)\"", "تست")]},
    "ansible": {"summary": "Ansible.", "lab": "ping module.", "cmds": [("ansible all -m ping", "تست")]},
    "kubernetes": {"summary": "K8s شبکه.", "lab": "pod network.", "cmds": [("kubectl get pods -A", "پادها")]},
}

ERRORS = {
    "vlan": ["VLAN mismatch روی trunk", "Native VLAN متفاوت", "پورت هنوز access است"],
    "stp": ["Root اشتباه", "BPDU filter ناخواسته", "Loop کابل"],
    "ospf": ["Neighbor گیر کرده", "Area mismatch", "Timer متفاوت"],
    "bgp": ["Peer Idle", "ASN اشتباه", "Update-source نادرست"],
    "dhcp": ["Pool پر", "Relay نادرست", "Conflict آدرس"],
    "dns": ["Forwarder قطع", "Zone fail", "Cache کهنه"],
    "vpn": ["Phase1 fail", "proxy-id mismatch", "NAT-T"],
    "firewall": ["order اشتباه", "object ناقص", "بدون hit"],
    "ha": ["اولویت اشتباه", "preempt", "heartbeat قطع"],
    "linux": ["سرویس fail", "Permission", "Route گم"],
    "windows": ["GPO اعمال نشده", "DNS اشتباه", "Firewall profile"],
    "wireless": ["SSID/VLAN", "تداخل کانال", "DHCP پس از association"],
    "general": ["پیکربندی با شواهد هم‌خوان نیست", "نسخه متفاوت", "محدوده مبهم"],
    "mikrotik": ["FastTrack conflict", "Route mark نادرست"],
    "fortigate": ["Policy hit صفر", "SSL inspection"],
    "ad": ["Replication lag", "DNS SRV"],
    "security": ["AAA timeout", "Certificate expired"],
    "tcpip": ["MTU", "Asymmetric routing"],
    "storage": ["Latency", "Path fail"],
    "virtualization": ["vSwitch uplink", "Resource contention"],
    "python": ["Auth fail", "Timeout"],
    "ansible": ["host unreachable", "Module missing"],
    "kubernetes": ["CNI", "endpoints خالی"],
}

SCENARIO_HOOKS = {
    "vlan": ["کاربران VLAN مهمان به سرور مالی دسترسی پیدا کردند — trunk و native را بررسی کنید."],
    "stp": ["پس از افزودن سوییچ، شبکه فلج شد — loop و Root."],
    "ospf": ["دو سایت adjacency نمی‌گیرند — area و timer."],
    "bgp": ["مسیر ISP دوم برنمی‌گردد — prefix-list."],
    "dhcp": ["کلاینت‌ها APIPA می‌گیرند — pool و relay."],
    "dns": ["نام داخلی resolve نمی‌شود — forwarder."],
    "vpn": ["تونل گاهی up می‌شود — Phase1."],
    "firewall": ["اپ جدید کار نمی‌کند — policy order."],
    "ha": ["Failover طول کشید — hello و tracking."],
    "linux": ["سرویس بعد از reboot بالا نمی‌آید."],
    "windows": ["GPO جدید دیده نمی‌شود."],
    "wireless": ["به SSID وصل می‌شود ولی IP ندارد."],
    "security": ["لاگین 802.1X fail."],
    "tcpip": ["انتقال فایل کند است."],
    "storage": ["VM کند — datastore latency."],
    "virtualization": ["VM شبکه ندارد."],
    "python": ["اسکریپت backup fail."],
    "ansible": ["playbook روی نیمی از hostها fail."],
    "general": ["سرویس قطع؛ Symptom→Evidence→Fix."],
    "mikrotik": ["اینترنت کند — queue و fasttrack."],
    "fortigate": ["VPN SSL وصل نمی‌شود."],
    "ad": ["لاگین دامنه کند است."],
    "kubernetes": ["Pod CrashLoop."],
    "cloud": ["Security group ترافیک را می‌بندد."],
    "backup": ["آخرین backup موفق نیست."],
    "monitoring": ["Alert طوفانی."],
    "voip": ["تماس یک‌طرفه."],
    "soc": ["هشدار SIEM بدون context."],
}

for _k in list(BANKS.keys()):
    if isinstance(_k, str) and _k != _k.upper():
        BANKS[_k.upper()] = BANKS[_k]
